.\" Copyright (c) 2007-2015 The OpenRC Authors.
.\" This file is part of the UQIS project. It is subject to the license terms in
.\" the LICENSE file found in the top-level directory of this
.\" distribution and at https://github.com/Uquinix/uqis/blob/HEAD/LICENSE
.\" This file may not be copied, modified, propagated, or distributed
.\"    except according to the terms contained in the LICENSE file.
.\"
.Dd Mar 16, 2008
.Dt RC_PLUGIN_HOOK 3 SMM
.Os UQIS
.Sh NAME
.Nm rc_plugin_hook
.Nd hooks plugins into UQIS services
.Sh LIBRARY
Run Command library (librc, -lrc)
.Sh SYNOPSIS
.In rc.h
.Ft int Fn rc_plugin_hook "RC_HOOK hook" "const char *name"
.Sh DESCRIPTION
.Fn rc_plugin_hook
is called for each shareable object found in
.Pa /lib/rc/plugins .
.Fa hook
is set to the hook running, and
.Fa name
is set to the name of the runlevel or name of the service.
.Pp
Plugins can affect the parent environment by writing NULL separated strings to
.Va rc_environ_fd .
.Sh SEE ALSO
.Xr uqis 8 ,
.Xr uqis-run 8
.Sh AUTHORS
.An Roy Marples <roy@marples.name>
