# Travis build integration.
# https://docs.travis-ci.com/

language: c

os:
  - linux

compiler:
  - gcc
  - clang
  - musl-gcc

addons:
  apt:
    packages:
    - musl-tools


before_install:
  - sudo apt-get update
  - sudo apt-get install -y shellcheck

script:
  - ./tools/ci/travis.sh
